const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

// Define __DEV__ for Node.js environment
const __DEV__ = process.env.NODE_ENV !== 'production';

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
    minifierConfig: {
      keep_fnames: true,
      mangle: {
        keep_fnames: true,
      },
      compress: {
        drop_console: !__DEV__,
        drop_debugger: !__DEV__,
        pure_funcs: !__DEV__ ? ['console.log', 'console.info', 'console.debug'] : [],
      },
    },
  },
  resolver: {
    // Enable tree shaking for better bundle optimization
    unstable_enableSymlinks: false,
    // Exclude only essential files from bundle
    blockList: [
      /.*\.test\.(js|ts|tsx)$/,
      /.*\.spec\.(js|ts|tsx)$/,
      /.*\.stories\.(js|ts|tsx)$/,
      /.*\.d\.ts$/,
      /.*\.map$/,
      /.*\.md$/,
      /.*\.lock$/,
      /.*\.log$/,
      /.*\.gitignore$/,
      /.*\.eslintrc$/,
      /.*\.prettierrc$/,
      /.*\.babelrc$/,
      /.*\.browserslistrc$/,
      /.*\.editorconfig$/,
      /.*\.npmrc$/,
      /.*\.yarnrc$/,
      /.*\.gitattributes$/,
      /.*\.gitmodules$/,
      /.*\.gitkeep$/,
      /.*\.DS_Store$/,
      /.*\.Thumbs.db$/,
    ],
    // Platform-specific extensions
    platforms: ['ios', 'android', 'native', 'web'],
    // Source map configuration
    sourceExts: ['js', 'jsx', 'ts', 'tsx', 'json'],
    // Asset extensions - allow all common asset types
    assetExts: [
      'png',
      'jpg',
      'jpeg',
      'gif',
      'webp',
      'svg',
      'ico',
      'bmp',
      'tiff',
      'tif',
      'heic',
      'heif',
      'avif',
      'jxl',
      'jp2',
      'j2k',
      'jpf',
      'jpx',
      'jpm',
      'mj2',
      'mp4',
      'mov',
      'avi',
      'mkv',
      'webm',
      'flv',
      'wmv',
      'm4v',
      '3gp',
      'ogv',
      'ogm',
      'mp3',
      'wav',
      'flac',
      'aac',
      'ogg',
      'wma',
      'm4a',
      'opus',
      'amr',
      'au',
      'ra',
      'mid',
      'midi',
      'kar',
      'rmi',
      'ttf',
      'otf',
      'woff',
      'woff2',
      'eot',
      'pdf',
      'doc',
      'docx',
      'xls',
      'xlsx',
      'ppt',
      'pptx',
      'zip',
      'rar',
      '7z',
      'tar',
      'gz',
      'bz2',
      'xz',
      'lzma',
      'lz',
      'lzo',
      'lz4',
      'zst',
      'zstd',
      'lzop',
      'lha',
      'lzh',
      'ace',
      'arj',
      'cab',
      'dmg',
      'iso',
      'img',
      'vhd',
      'vmdk',
      'vdi',
      'qcow',
      'qcow2',
      'vbox',
      'ova',
      'ovf',
      'ovd',
      'ovt',
      'ovs',
      'ovx',
      'ovm',
      'ovc',
      'ovb',
      'ovn',
      'ovp',
      'ovq',
      'ovr',
      'ovs',
      'ovt',
      'ovu',
      'ovv',
      'ovw',
      'ovx',
      'ovy',
      'ovz',
      'ov0',
      'ov1',
      'ov2',
      'ov3',
      'ov4',
      'ov5',
      'ov6',
      'ov7',
      'ov8',
      'ov9',
      'ov10',
      'ov11',
      'ov12',
      'ov13',
      'ov14',
      'ov15',
      'ov16',
      'ov17',
      'ov18',
      'ov19',
      'ov20',
      'ov21',
      'ov22',
      'ov23',
      'ov24',
      'ov25',
      'ov26',
      'ov27',
      'ov28',
      'ov29',
      'ov30',
      'ov31',
      'ov32',
      'ov33',
      'ov34',
      'ov35',
      'ov36',
      'ov37',
      'ov38',
      'ov39',
      'ov40',
      'ov41',
      'ov42',
      'ov43',
      'ov44',
      'ov45',
      'ov46',
      'ov47',
      'ov48',
      'ov49',
      'ov50',
      'ov51',
      'ov52',
      'ov53',
      'ov54',
      'ov55',
      'ov56',
      'ov57',
      'ov58',
      'ov59',
      'ov60',
      'ov61',
      'ov62',
      'ov63',
      'ov64',
      'ov65',
      'ov66',
      'ov67',
      'ov68',
      'ov69',
      'ov70',
      'ov71',
      'ov72',
      'ov73',
      'ov74',
      'ov75',
      'ov76',
      'ov77',
      'ov78',
      'ov79',
      'ov80',
      'ov81',
      'ov82',
      'ov83',
      'ov84',
      'ov85',
      'ov86',
      'ov87',
      'ov88',
      'ov89',
      'ov90',
      'ov91',
      'ov92',
      'ov93',
      'ov94',
      'ov95',
      'ov96',
      'ov97',
      'ov98',
      'ov99',
      'ov100',
    ],
  },
  // Optimize bundle size
  serializer: {
    // Enable tree shaking
    experimentalSerializerHook: () => {},
  },
  // Cache configuration - using default cache store
  // Watchman configuration
  watchFolders: [],
  // Server configuration
  server: {
    port: 8081,
    enhanceMiddleware: (middleware) => {
      return (req, res, next) => {
        // Add custom headers for security
        res.setHeader('X-Content-Type-Options', 'nosniff');
        res.setHeader('X-Frame-Options', 'DENY');
        res.setHeader('X-XSS-Protection', '1; mode=block');
        return middleware(req, res, next);
      };
    },
  },
  // Max workers for parallel processing
  maxWorkers: require('os').cpus().length,
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
