export const WORD_DIR = {
  welcomeMsg: 'Welcome to the app!',
  firstName: 'First name',
  lastName: 'Last name',
  username: 'Username',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  forgotPassword: 'Forgot Password',
  login: 'Login',
  register: 'Register',
  registerUser:'User registration successful',
  verificationFailed:"Verification failed. Please try again.",
  haveAnAccount: 'Already have an account? ',
  dontHaveAnAccount: "Don't have an account? ",
  emailOTP: 'Enter email OTP',
  phoneOTP: 'Enter phone OTP',
  verifyOTP: 'Verify OTP',
  upcomingEvents: 'Upcoming events',

  serviceDetails: 'Service Details',
  
  title: 'Title',
  description: 'Description',
  chargesPerHour: 'Charges per hour',
  selectDate: 'Select Date',
  selectTimeSlots: 'Select Time Slots',
  next: 'Next',
  createService: 'Create Service',

  userNotFound: 'User not found',
  submit: 'Submit',

  paymentSummary: 'Payment summary',

  amount: 'Amount',
  tax: 'Tax',
  total: 'Total Payment',
  continue:"Continue",
  choosePayment:"Choose Payment Method",
  secureTransaction:"All transactions are secure and encrypted.",

  emptyCartHeading:'Your cart is empty!',
  emptyCartSubHeading:'Choose a service and proceed to checkout',
  goHome:"Go To Home",
  noService:"Oops! Not service found",
  noUpcomingEvents:"Opps! No Upcoming events",
  scheduleEvent:"Schedule and event to view upcoming events",

  notificationPreference: 'Notification preference',
  enableMobilePushNotifications: 'Enable Mobile Push Notifications',
  enableEmailPushNotifications: 'Enable Email Push Notifications',
  mobileNotification: 'Mobile Notification',
  emailNotification: 'Email Notification',
  selectInterests: 'Let\'s select your interests.',
  selectTwoOrMore: 'Please select two or more to proceed.',
  saveSettings: 'Save Settings',
  settingsUpdated: 'Settings updated!',
};
