export const WORD_DIR  ={
    name:"Name",
    username:"Username",
    email:"Email",
    password:"Password",
    confirmPassword:"Confirm Password",
    forgotPassword:"Forgot Password",
    login:"Login",
    register:"Register",
    haveAnAccount:"Already have an account ?",
    dontHaveAnAccount:"Don't have an account ?",

    serviceDetails:"Service Details",
    title:"Title",
    description:"Description",
    costPerHour:"Cost per hour",
    selectDate:"Select Date",
    selectTimeSlots:'Select Time Slots',
    createService:"Create Service",
}