export const WORD_DIR = {
  welcomeText: 'Welcome to Harmoniq',
  welcomeSubText:
    'Discover amazing artists and book live performances that will make your event truly memorable.',
  loginHeading: 'Welcome Back',
  loginSubHeading: 'Enter your details below',
  registerHeading: 'Get started for free',
  registerSubHeading: 'Register now to find your favourite artist',
  firstName: 'First name',
  lastName: 'Last name',
  username: 'Username',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  forgotPassword: 'Forgot your password?',
  login: 'Login',
  register: 'Register',
  registerUser: 'User registration successful',
  verificationFailed: 'Verification failed. Please try again.',
  haveAnAccount: 'Already have an account?',
  dontHaveAnAccount: "Don't have an account?",
  emailOTP: 'Enter email OTP',
  phoneOTP: 'Enter phone OTP',
  verifyOTP: 'Verify OTP',
  upcomingEvents: 'Upcoming events',
  serviceDetails: 'Service Details',
  serviceProviderEnrollment:"Become a Service Provider",
  title: 'Title',
  description: 'Description',
  pricing: 'Pricing',
  selectDate: 'Select Date',
  selectTimeSlots: 'Select Time Slots',
  next: 'Next',
  createService: 'Create Service',
  whyEnroll:'Why become a service provider?',

  userNotFound: 'User not found',
  submit: 'Submit',

  paymentSummary: 'Payment summary',

  amount: 'Amount',
  tax: 'Tax',
  total: 'Total Payment',
  continue: 'Continue',
  choosePayment: 'Choose Payment Method',
  secureTransaction: 'All transactions are secure and encrypted.',

  emptyCartHeading: 'Your cart is empty!',
  emptyCartSubHeading: 'Choose a service and proceed to checkout',
  goHome: 'Go To Home',
  noService: 'Oops! Not service found',
  noSchedule: 'There are no dates been scheduled by the service provider',
  noUpcomingEvents: 'Opps! No Upcoming events',
  scheduleEvent: 'Schedule and event to view upcoming events',

  notificationPreference: 'Notification preference',
  enableMobilePushNotifications: 'Enable Mobile Push Notifications',
  enableEmailPushNotifications: 'Enable Email Push Notifications',
  mobileNotification: 'Mobile Notification',
  emailNotification: 'Email Notification',
  selectInterests: "Let's select your interests.",
  selectTwoOrMore: 'Please select two or more to proceed.',
  saveSettings: 'Save Settings',
  settingsUpdated: 'Settings updated!',
  tnc:"Terms and Conditions"
};
